// Machine list from tblMachineDetails (exported 2026-06-03).
// Each row is [machine_code, machine_desc, location]. The machine_code is the value inside the QR code.
// To update the list, replace the rows below with the new export.
export const MACHINE_ROWS = [
  ["F36-B", "Additive Feeder", "Bran B - 2nd Floor"],
  ["LSB20-B", "Limit Switch", "Bran B - 2nd Floor"],
  ["WXZD-03", "Tubular Screw Conveyor", "Bran B - 2nd Floor"],
  ["B20c-B", "Tubular Screw Conveyor", "Bran B - 2nd Floor"],
  ["B20d-B", "Tubular Screw Conveyor", "Bran B - 2nd Floor"],
  ["B19b-B", "Vibro Discharger", "Bran B - 2nd Floor"],
  ["B19c-B", "Vibro Discharger", "Bran B - 2nd Floor"],
  ["B19d-B", "Vibro Discharger", "Bran B - 2nd Floor"],
  ["B19A-B", "Vibro Discharger", "Bran B - 2nd Floor"],
  ["BRAN-A", "Two Way Valve Bran", "Bran B - 6th Floor"],
  ["H06", "Compressor", "Compressor Room Mill A"],
  ["D06", "Air Dryer", "Compressor Room Mill A"],
  ["MMG-AD-010", "Auto Drain", "Compressor Room Mill A"],
  ["H00", "Compressor", "Compressor Room Mill A"],
  ["H01", "Compressor", "Compressor Room Mill A"],
  ["D00", "Air Dryer", "Compressor Room Mill A"],
  ["D01", "Air Dryer", "Compressor Room Mill A"],
  ["MMG-AD-014", "Auto Drain", "Compressor Room Mill B"],
  ["MMG-AD-013", "Auto Drain", "Compressor Room Mill B"],
  ["MMG-AD-011", "Auto Drain", "Compressor Room Mill B"],
  ["MMG-AD-012", "Auto Drain", "Compressor Room Mill B"],
  ["MMG-AD-009", "Auto Drain", "Compressor Room Mill B"],
  ["MMG-AD-008", "Auto Drain", "Compressor Room Mill B"],
  ["MMG-AD-007", "Auto Drain", "Compressor Room Mill B"],
  ["MMG-AD-006", "Auto Drain", "Compressor Room Mill B"],
  ["MMG-AD-005", "Auto Drain", "Compressor Room Mill B"],
  ["MMG-AD-003", "Auto Drain", "Compressor Room Mill B"],
  ["MMG-AD-004", "Auto Drain", "Compressor Room Mill B"],
  ["MMG-AD-002", "Auto Drain", "Compressor Room Mill B"],
  ["MMG-AD-001", "Auto Drain", "Compressor Room Mill B"],
  ["D03", "Air Dryer", "Compressor Room Mill B"],
  ["D02", "Air Dryer", "Compressor Room Mill B"],
  ["H02", "Compressor", "Compressor Room Mill B"],
  ["H03", "Compressor", "Compressor Room Mill B"],
  ["H04", "Compressor", "Compressor Room Mill B"],
  ["H05", "Compressor", "Compressor Room Mill B"],
  ["D04", "Air Dryer", "Compressor Room Mill B"],
  ["D05", "Air Dryer", "Compressor Room Mill B"],
  ["=+CB17-1", "Electrical Panel Board", "LVSG - Mill B"],
  ["=+CB17-2", "Electrical Panel Board", "LVSG - Mill B"],
  ["C03b-A", "Flow Balancer", "Mill A - 1st Floor"],
  ["C24b-A", "Flow Balancer", "Mill A - 1st Floor"],
  ["L2A", "Packer Single Spout", "Mill A - 1st Floor"],
  ["M02-A", "Rollermill", "Mill A - 1st Floor"],
  ["M17-A", "Rollermill", "Mill A - 1st Floor"],
  ["TVSS- 04", "TVSS (Transient voltage surge suppressor)", "Mill A - 1st Floor"],
  ["TVSS- 06", "TVSS (Transient voltage surge suppressor)", "Mill A - 1st Floor"],
  ["TVSS- 07", "TVSS (Transient voltage surge suppressor)", "Mill A - 1st Floor"],
  ["TVSS- 08", "TVSS (Transient voltage surge suppressor)", "Mill A - 1st Floor"],
  ["TVSS- 15", "TVSS (Transient voltage surge suppressor)", "Mill A - 1st Floor"],
  ["A-MCC07", "Electrical Panel Board", "Mill A - 1st Floor"],
  ["A-MCC08", "Electrical Panel Board", "Mill A - 1st Floor"],
  ["TVSS- 16", "TVSS (Transient voltage surge suppressor)", "Mill A - 1st Floor"],
  ["A-MCC09", "Electrical Panel Board", "Mill A - 1st Floor"],
  ["TVSS- 13", "TVSS (Transient voltage surge suppressor)", "Mill A - 1st Floor"],
  ["A-MDB04", "Electrical Panel Board", "Mill A - 1st Floor"],
  ["A-PLC01", "Electrical Panel Board", "Mill A - 1st Floor"],
  ["A-VFD", "Electrical Panel Board", "Mill A - 1st Floor"],
  ["P37-A", "Airlock", "Mill A - 1st Floor"],
  ["P29-A", "Airlock", "Mill A - 1st Floor"],
  ["P03-A", "Airlock", "Mill A - 1st Floor"],
  ["P09-A", "Airlock", "Mill A - 1st Floor"],
  ["P35-A", "Automatic Scale", "Mill A - 1st Floor"],
  ["P27-A", "Automatic Scale", "Mill A - 1st Floor"],
  ["P57-A", "Belt Conveyor A", "Mill A - 1st Floor"],
  ["P56-A", "Belt Conveyor A", "Mill A - 1st Floor"],
  ["P04-A", "Blower", "Mill A - 1st Floor"],
  ["P10-A", "Blower", "Mill A - 1st Floor"],
  ["P38-A", "Blower", "Mill A - 1st Floor"],
  ["P30-A", "Blower", "Mill A - 1st Floor"],
  ["C03c-A", "Flow Balancer", "Mill A - 1st Floor"],
  ["C24f-A", "Flow Balancer", "Mill A - 1st Floor"],
  ["C24e-A", "Flow Balancer", "Mill A - 1st Floor"],
  ["C24d-A", "Flow Balancer", "Mill A - 1st Floor"],
  ["C24c-A", "Flow Balancer", "Mill A - 1st Floor"],
  ["C24a-A", "Flow Balancer", "Mill A - 1st Floor"],
  ["C03-A", "Flow Balancer", "Mill A - 1st Floor"],
  ["D208-B", "Flow Balancer", "Mill A - 1st Floor"],
  ["C45-A", "Hammermill", "Mill A - 1st Floor"],
  ["M06-A", "Rollermill", "Mill A - 1st Floor"],
  ["M16-A", "Rollermill", "Mill A - 1st Floor"],
  ["M14-A", "Rollermill", "Mill A - 1st Floor"],
  ["M15-A", "Rollermill", "Mill A - 1st Floor"],
  ["M07-A", "Rollermill", "Mill A - 1st Floor"],
  ["M19-A", "Rollermill", "Mill A - 1st Floor"],
  ["M08-A", "Rollermill", "Mill A - 1st Floor"],
  ["M18-A", "Rollermill", "Mill A - 1st Floor"],
  ["M09-A", "Rollermill", "Mill A - 1st Floor"],
  ["M10-A", "Rollermill", "Mill A - 1st Floor"],
  ["M20-A", "Rollermill", "Mill A - 1st Floor"],
  ["M01-A", "Rollermill", "Mill A - 1st Floor"],
  ["M03-A", "Rollermill", "Mill A - 1st Floor"],
  ["M04-A", "Rollermill", "Mill A - 1st Floor"],
  ["M13-A", "Rollermill", "Mill A - 1st Floor"],
  ["M11-A", "Rollermill", "Mill A - 1st Floor"],
  ["M12-A", "Rollermill", "Mill A - 1st Floor"],
  ["M05-A", "Rollermill", "Mill A - 1st Floor"],
  ["C04-A", "Screw Conveyor", "Mill A - 1st Floor"],
  ["C25-A", "Screw Conveyor", "Mill A - 1st Floor"],
  ["C26-A", "Screw Conveyor", "Mill A - 1st Floor"],
  ["C26a-A", "Screw Conveyor", "Mill A - 1st Floor"],
  ["C26b-A", "Screw Conveyor", "Mill A - 1st Floor"],
  ["C40-A", "Screw Conveyor", "Mill A - 1st Floor"],
  ["C43-A", "Tubular Screw Conveyor", "Mill A - 1st Floor"],
  ["M59-A", "Vibro Feeder", "Mill A - 1st Floor"],
  ["PSP04-A", "Blower Switch", "Mill A - 1st Floor"],
  ["PSP10-A", "Blower Switch", "Mill A - 1st Floor"],
  ["PSP30-A", "Blower Switch", "Mill A - 1st Floor"],
  ["PSP38-A", "Blower Switch", "Mill A - 1st Floor"],
  ["P20-A", "Sewing Machine", "Mill A - 1st Floor"],
  ["P25-A", "Sewing Machine", "Mill A - 1st Floor"],
  ["P64-A", "Blower", "Mill A - 1st Floor"],
  ["P65-A", "Airlock", "Mill A - 1st Floor"],
  ["L1A", "Packer Single Spout", "Mill A - 1st Floor"],
  ["LSC-A", "Limit Switch", "Mill A - 1st-4th Floor"],
  ["M30a-A", "Additive Feeder", "Mill A - 2nd Floor"],
  ["P01-A", "Automatic Scale", "Mill A - 2nd Floor"],
  ["C46-A", "High Pressure Jet Filter", "Mill A - 2nd Floor"],
  ["M22-A", "Purifier", "Mill A - 2nd Floor"],
  ["P14A-A", "Tubular Screw Conveyor", "Mill A - 2nd Floor"],
  ["P13A-A", "Vibro Discharger", "Mill A - 2nd Floor"],
  ["F05-A", "Hammermill", "Mill A - 2nd Floor"],
  ["A-MCC02", "Electrical Panel Board", "Mill A - 2nd Floor"],
  ["A-MCC04", "Electrical Panel Board", "Mill A - 2nd Floor"],
  ["A-MCC05", "Electrical Panel Board", "Mill A - 2nd Floor"],
  ["A-MCC06", "Electrical Panel Board", "Mill A - 2nd Floor"],
  ["A-MCC03", "Electrical Panel Board", "Mill A - 2nd Floor"],
  ["A-MDB02", "Electrical Panel Board", "Mill A - 2nd Floor"],
  ["A-MDB03", "Electrical Panel Board", "Mill A - 2nd Floor"],
  ["M29-A", "Additive Feeder", "Mill A - 2nd Floor"],
  ["M30-A", "Additive Feeder", "Mill A - 2nd Floor"],
  ["M31-A", "Additive Feeder", "Mill A - 2nd Floor"],
  ["M32-A", "Additive Feeder", "Mill A - 2nd Floor"],
  ["M29a-A", "Additive Feeder", "Mill A - 2nd Floor"],
  ["M60-A", "Additive Feeder", "Mill A - 2nd Floor"],
  ["M068a-B", "Additive Feeder", "Mill A - 2nd Floor"],
  ["C35-A", "Air Aspiration Channel", "Mill A - 2nd Floor"],
  ["P07-A", "Automatic Scale", "Mill A - 2nd Floor"],
  ["C39-A", "Automatic Scale", "Mill A - 2nd Floor"],
  ["M24a-A", "Bran Finisher", "Mill A - 2nd Floor"],
  ["M25a-A", "Bran Finisher", "Mill A - 2nd Floor"],
  ["M24-A", "Bran Finisher", "Mill A - 2nd Floor"],
  ["M25-A", "Bran Finisher", "Mill A - 2nd Floor"],
  ["C10-A", "Gravity Classifying Destoner", "Mill A - 2nd Floor"],
  ["F07-A", "Jet Filter", "Mill A - 2nd Floor"],
  ["LSP-A", "Limit Switch", "Mill A - 2nd Floor"],
  ["M21-A", "Purifier", "Mill A - 2nd Floor"],
  ["M23-A", "Purifier", "Mill A - 2nd Floor"],
  ["F01-A", "Screw Conveyor", "Mill A - 2nd Floor"],
  ["F06-A", "Screw Conveyor", "Mill A - 2nd Floor"],
  ["M27-A", "Screw Conveyor", "Mill A - 2nd Floor"],
  ["M28-A", "Screw Conveyor", "Mill A - 2nd Floor"],
  ["P14-A", "Tubular Screw Conveyor", "Mill A - 2nd Floor"],
  ["P15-A", "Tubular Screw Conveyor", "Mill A - 2nd Floor"],
  ["P14B-A", "Tubular Screw Conveyor", "Mill A - 2nd Floor"],
  ["P14C-A", "Tubular Screw Conveyor", "Mill A - 2nd Floor"],
  ["P13C-A", "Vibro Discharger", "Mill A - 2nd Floor"],
  ["P13B-A", "Vibro Discharger", "Mill A - 2nd Floor"],
  ["P13-A", "Vibro Discharger", "Mill A - 2nd Floor"],
  ["M26-A", "Vibro Feeder", "Mill A - 2nd Floor"],
  ["C34-A", "Vibro Separator", "Mill A - 2nd Floor"],
  ["P22-A", "Check Sifter", "Mill A - 3rd Floor"],
  ["C15-A", "Horizontal Scourer", "Mill A - 3rd Floor"],
  ["C16-A", "Air Aspiration Channel", "Mill A - 3rd Floor"],
  ["C41C-A", "Automatic Scale", "Mill A - 3rd Floor"],
  ["P17-A", "Check Sifter", "Mill A - 3rd Floor"],
  ["P48-A", "High Pressure Jet Filter", "Mill A - 3rd Floor"],
  ["C33-A", "Horizontal Scourer", "Mill A - 3rd Floor"],
  ["F03-A", "Low Pressure Fan", "Mill A - 3rd Floor"],
  ["C11-A", "Low Pressure Fan", "Mill A - 3rd Floor"],
  ["F02-A", "Low Pressure Jet Filter", "Mill A - 3rd Floor"],
  ["M33-A", "Plansifter", "Mill A - 3rd Floor"],
  ["M34-A", "Plansifter", "Mill A - 3rd Floor"],
  ["M35-A", "Plansifter", "Mill A - 3rd Floor"],
  ["P51-A", "Rebolt Sifter", "Mill A - 3rd Floor"],
  ["M44-A", "Impact Detacher", "Mill A - 4th Floor"],
  ["C00B-A", "Insert Bag Filter", "Mill A - 4th Floor"],
  ["A-UVL01", "Ultraviolet Sterilizer", "Mill A - 4th Floor"],
  ["M51-A", "Impact Detacher", "Mill A - 4th Floor"],
  ["P54-A", "Airlock", "Mill A - 4th Floor"],
  ["M56A-A", "Airlock", "Mill A - 4th Floor"],
  ["M58A-A", "Airlock", "Mill A - 4th Floor"],
  ["C09-A", "Air Aspiration Channel", "Mill A - 4th Floor"],
  ["P53-A", "Bucket Elevator", "Mill A - 4th Floor"],
  ["C41-A", "Bucket Elevator", "Mill A - 4th Floor"],
  ["P16-A", "Bucket Elevator", "Mill A - 4th Floor"],
  ["M36-A", "Cyclone Airlock Batch", "Mill A - 4th Floor"],
  ["M37-A", "Cyclone Airlock Batch", "Mill A - 4th Floor"],
  ["M38-A", "Cyclone Airlock Batch", "Mill A - 4th Floor"],
  ["M39-A", "Cyclone Airlock Batch", "Mill A - 4th Floor"],
  ["M40-A", "Cyclone Airlock Batch", "Mill A - 4th Floor"],
  ["M41-A", "Cyclone Airlock Batch", "Mill A - 4th Floor"],
  ["C19-A", "Dampener Mixer", "Mill A - 4th Floor"],
  ["C20-A", "Dampening Conveyor", "Mill A - 4th Floor"],
  ["M43-A", "Drum Detacher", "Mill A - 4th Floor"],
  ["M46-A", "Drum Detacher", "Mill A - 4th Floor"],
  ["M47-A", "Drum Detacher", "Mill A - 4th Floor"],
  ["C32a-A", "Gravity Classifying Destoner", "Mill A - 4th Floor"],
  ["HLC-A", "High Level Sensor", "Mill A - 4th Floor"],
  ["C47-A", "Low Pressure Fan", "Mill A - 4th Floor"],
  ["M57-A", "High Pressure Fan", "Mill A - 4th Floor"],
  ["M56-A", "High Pressure Jet Filter", "Mill A - 4th Floor"],
  ["M58-A", "High Pressure Jet Filter", "Mill A - 4th Floor"],
  ["M48-A", "Impact Detacher", "Mill A - 4th Floor"],
  ["M45-A", "Impact Detacher", "Mill A - 4th Floor"],
  ["M49-A", "Impact Detacher", "Mill A - 4th Floor"],
  ["M50-A", "Impact Detacher", "Mill A - 4th Floor"],
  ["M52-A", "Impact Detacher", "Mill A - 4th Floor"],
  ["M53-A", "Impact Detacher", "Mill A - 4th Floor"],
  ["M54-A", "Impact Detacher", "Mill A - 4th Floor"],
  ["M42-A", "Impact Detacher", "Mill A - 4th Floor"],
  ["P06a-A", "Infestation Destroyer", "Mill A - 4th Floor"],
  ["P06b-A", "Infestation Destroyer", "Mill A - 4th Floor"],
  ["P16a-A", "Infestation Destroyer", "Mill A - 4th Floor"],
  ["P16b-A", "Infestation Destroyer", "Mill A - 4th Floor"],
  ["C00A-A", "Insert Bag Filter", "Mill A - 4th Floor"],
  ["C00-A", "Insert Bag Filter", "Mill A - 4th Floor"],
  ["M55-A", "Low Pressure Fan", "Mill A - 4th Floor"],
  ["C08-A", "Vibro Separator", "Mill A - 4th Floor"],
  ["C18-A", "Water Addition System", "Mill A - 4th Floor"],
  ["C49A-A", "Airlock", "Mill A - 5th Floor"],
  ["C05-A", "Bucket Elevator", "Mill A - 5th Floor"],
  ["TVSS- 05", "TVSS (Transient voltage surge suppressor)", "Mill A - 5th Floor"],
  ["C29A-A", "Airlock", "Mill A - 5th Floor"],
  ["C07-A", "Automatic Scale", "Mill A - 5th Floor"],
  ["C12-A", "Bucket Elevator", "Mill A - 5th Floor"],
  ["C17-A", "Bucket Elevator", "Mill A - 5th Floor"],
  ["C27-A", "Bucket Elevator", "Mill A - 5th Floor"],
  ["C36-A", "Bucket Elevator", "Mill A - 5th Floor"],
  ["HLF-A", "High Level Sensor", "Mill A - 5th Floor"],
  ["C49-A", "High Pressure Jet Filter", "Mill A - 5th Floor"],
  ["C29-A", "High Pressure Jet Filter", "Mill A - 5th Floor"],
  ["P50-A", "Low Pressure Fan", "Mill A - 5th Floor"],
  ["C28-A", "Low Pressure Fan", "Mill A - 5th Floor"],
  ["C48-A", "Low Pressure Fan", "Mill A - 5th Floor"],
  ["MDB02-A", "Control Panel", "Mill A - MCC Room"],
  ["MDB04-A", "Control Panel", "Mill A - MCC Room"],
  ["MDB03-A", "Control Panel", "Mill A - MCC Room"],
  ["MDB03-B", "Control Panel", "Mill A - MCC Room"],
  ["MDB02-B", "Control Panel", "Mill A - MCC Room"],
  ["PP-GGI01", "Electrical Panel Board - 1", "Mill A - Packing Area"],
  ["PP-GGI02", "Electrical Panel Board - 1", "Mill A - Packing Area"],
  ["QCA-QC-E-032", "Vibro Shaker", "Mill A - Packing Area"],
  ["SE-A", "Service Elevator", "Mill A Building"],
  ["P1-1", "Belt Conveyor", "Mill B - 1st Floor"],
  ["B11-B", "Blower", "Mill B - 1st Floor"],
  ["F05-B", "Blower", "Mill B - 1st Floor"],
  ["D202-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["M021-B", "Rollermill", "Mill B - 1st Floor"],
  ["M018-B", "Rollermill", "Mill B - 1st Floor"],
  ["M020-B", "Rollermill", "Mill B - 1st Floor"],
  ["M008-B", "Rollermill", "Mill B - 1st Floor"],
  ["M034-B", "Rollermill", "Mill B - 1st Floor"],
  ["M026-B", "Rollermill", "Mill B - 1st Floor"],
  ["C29a-B", "Screw Conveyor", "Mill B - 1st Floor"],
  ["B-M7103", "Positive Airlock", "Mill B - 1st Floor"],
  ["B-M7104", "Positive Airlock", "Mill B - 1st Floor"],
  ["B-MCC01", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MCC02", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MCC03", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MCC04", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-M710", "Air Cooler", "Mill B - 1st Floor"],
  ["B-MCC05", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MCC06", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MCC08", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MCC09", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MCC07", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MCC10", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MCC11", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MCC12", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MCC13", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["TVSS- 11", "TVSS (Transient voltage surge suppressor)", "Mill B - 1st Floor"],
  ["B-MDB01", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MDB02", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MDB03", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-MDB04", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["TVSS- 12", "TVSS (Transient voltage surge suppressor)", "Mill B - 1st Floor"],
  ["TVSS- 17", "TVSS (Transient voltage surge suppressor)", "Mill B - 1st Floor"],
  ["TVSS- 18", "TVSS (Transient voltage surge suppressor)", "Mill B - 1st Floor"],
  ["B-PLC02", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["B-PLC01", "Electrical Panel Board", "Mill B - 1st Floor"],
  ["ET02", "Electrical Panel Board - 1", "Mill B - 1st Floor"],
  ["B-LL7110B", "Low Level Sensor", "Mill B - 1st Floor"],
  ["B-M7101", "Blower", "Mill B - 1st Floor"],
  ["B-HL7104", "High Level - BS", "Mill B - 1st Floor"],
  ["B-HL7103", "High Level - BS", "Mill B - 1st Floor"],
  ["B10-B", "Airlock", "Mill B - 1st Floor"],
  ["B04-B", "Airlock", "Mill B - 1st Floor"],
  ["B16-B", "Aspiration Valve", "Mill B - 1st Floor"],
  ["P2-1", "Belt Conveyor", "Mill B - 1st Floor"],
  ["F13-B", "Blower", "Mill B - 1st Floor"],
  ["F21-B", "Blower", "Mill B - 1st Floor"],
  ["B05-B", "Blower", "Mill B - 1st Floor"],
  ["D201-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["D203-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["D204-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["D209-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["D207-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["D206-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["D205-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["D101-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["D102-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["D103-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["D104-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["D105-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["D106-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["C02-B", "Flow Balancer", "Mill B - 1st Floor"],
  ["C48-B", "Hammermill", "Mill B - 1st Floor"],
  ["F60-B", "Packer Carousell", "Mill B - 1st Floor"],
  ["B24-B", "Packer Single Spout", "Mill B - 1st Floor"],
  ["M011-B", "Rollermill", "Mill B - 1st Floor"],
  ["M012-B", "Rollermill", "Mill B - 1st Floor"],
  ["M033-B", "Rollermill", "Mill B - 1st Floor"],
  ["M030-B", "Rollermill", "Mill B - 1st Floor"],
  ["M031-B", "Rollermill", "Mill B - 1st Floor"],
  ["M032-B", "Rollermill", "Mill B - 1st Floor"],
  ["M029-B", "Rollermill", "Mill B - 1st Floor"],
  ["M015-B", "Rollermill", "Mill B - 1st Floor"],
  ["M006-B", "Rollermill", "Mill B - 1st Floor"],
  ["M016-B", "Rollermill", "Mill B - 1st Floor"],
  ["M013-B", "Rollermill", "Mill B - 1st Floor"],
  ["M014-B", "Rollermill", "Mill B - 1st Floor"],
  ["M037-B", "Rollermill", "Mill B - 1st Floor"],
  ["M039-B", "Rollermill", "Mill B - 1st Floor"],
  ["M040-B", "Rollermill", "Mill B - 1st Floor"],
  ["M038-B", "Rollermill", "Mill B - 1st Floor"],
  ["M017-B", "Rollermill", "Mill B - 1st Floor"],
  ["M041-B", "Rollermill", "Mill B - 1st Floor"],
  ["M042-B", "Rollermill", "Mill B - 1st Floor"],
  ["M019-B", "Rollermill", "Mill B - 1st Floor"],
  ["M022-B", "Rollermill", "Mill B - 1st Floor"],
  ["M043-B", "Rollermill", "Mill B - 1st Floor"],
  ["M044-B", "Rollermill", "Mill B - 1st Floor"],
  ["M028-B", "Rollermill", "Mill B - 1st Floor"],
  ["M001-B", "Rollermill", "Mill B - 1st Floor"],
  ["M002-B", "Rollermill", "Mill B - 1st Floor"],
  ["M023-B", "Rollermill", "Mill B - 1st Floor"],
  ["M024-B", "Rollermill", "Mill B - 1st Floor"],
  ["M005-B", "Rollermill", "Mill B - 1st Floor"],
  ["M009-B", "Rollermill", "Mill B - 1st Floor"],
  ["M010-B", "Rollermill", "Mill B - 1st Floor"],
  ["M007-B", "Rollermill", "Mill B - 1st Floor"],
  ["M027-B", "Rollermill", "Mill B - 1st Floor"],
  ["M003-B", "Rollermill", "Mill B - 1st Floor"],
  ["M004-B", "Rollermill", "Mill B - 1st Floor"],
  ["M025-B", "Rollermill", "Mill B - 1st Floor"],
  ["M035-B", "Rollermill", "Mill B - 1st Floor"],
  ["M036-B", "Rollermill", "Mill B - 1st Floor"],
  ["C03-B", "Screw Conveyor", "Mill B - 1st Floor"],
  ["C04-B", "Screw Conveyor", "Mill B - 1st Floor"],
  ["C29b-B", "Screw Conveyor", "Mill B - 1st Floor"],
  ["C41-B", "Screw Conveyor", "Mill B - 1st Floor"],
  ["C46-B", "Screw Conveyor", "Mill B - 1st Floor"],
  ["F43-B", "Tubular Screw Conveyor", "Mill B - 1st Floor"],
  ["F42-B", "Vibro Discharger", "Mill B - 1st Floor"],
  ["PSB06-B", "Blower Switch", "Mill B - 1st Floor"],
  ["PSB12-B", "Blower Switch", "Mill B - 1st Floor"],
  ["PSF06-B", "Blower Switch", "Mill B - 1st Floor"],
  ["PSF14-B", "Blower Switch", "Mill B - 1st Floor"],
  ["PSF22-B", "Blower Switch", "Mill B - 1st Floor"],
  ["B26-B", "Sewing Machine", "Mill B - 1st Floor"],
  ["B27-B", "Sewing Machine", "Mill B - 1st Floor"],
  ["F61-B", "Sewing Machine", "Mill B - 1st Floor"],
  ["M2-B", "Sewing Machine", "Mill B - 1st Floor"],
  ["F60A-B", "Packer Carousell", "Mill B - 1st Floor and 2nd Floor"],
  ["B-M7111", "Tubular Screw Conveyor", "Mill B - 1st Floor Extension"],
  ["B-M7112", "Blower", "Mill B - 1st Floor Extension"],
  ["B-M7113", "Air Cooler", "Mill B - 1st Floor Extension"],
  ["B-M7114", "Positive Airlock", "Mill B - 1st Floor Extension"],
  ["B-LL7111", "Limit Switch - BS", "Mill B - 1st Floor Extension"],
  ["B-LL7110A", "Low Level Sensor", "Mill B - 1st Floor Extension"],
  ["B-HL7114", "High Level - BS", "Mill B - 1st Floor Extension"],
  ["LSC-B", "Limit Switch", "Mill B - 1st-5th Floor"],
  ["C29-B", "Screw Conveyor", "Mill B - 1st-5th Floor"],
  ["C16-B", "Horizontal Scourer", "Mill B - 2nd Floor"],
  ["F35-B", "Scale and Mixer", "Mill B - 2nd Floor"],
  ["BL-02", "Blender 300KG", "Mill B - 2nd Floor"],
  ["TVSS- 10", "TVSS (Transient voltage surge suppressor)", "Mill B - 2nd Floor"],
  ["BL-01", "Blender 200KG", "Mill B - 2nd Floor"],
  ["NIR", "Inline-NIR", "Mill B - 2nd Floor"],
  ["C17-B", "Air Recyling Aspirator", "Mill B - 2nd Floor"],
  ["F12-B", "Airlock", "Mill B - 2nd Floor"],
  ["F20-B", "Airlock", "Mill B - 2nd Floor"],
  ["F04-B", "Airlock", "Mill B - 2nd Floor"],
  ["B02-B", "Airlock", "Mill B - 2nd Floor"],
  ["B08-B", "Airlock", "Mill B - 2nd Floor"],
  ["F37-B", "Automatic Scale", "Mill B - 2nd Floor"],
  ["B07-B", "Automatic Scale", "Mill B - 2nd Floor"],
  ["B01-B", "Automatic Scale", "Mill B - 2nd Floor"],
  ["C50-B", "Automatic Scale", "Mill B - 2nd Floor"],
  ["F68A-B", "Check Sifter", "Mill B - 2nd Floor"],
  ["F07-B", "Infestation Destroyer", "Mill B - 2nd Floor"],
  ["F15-B", "Infestation Destroyer", "Mill B - 2nd Floor"],
  ["B21-B", "Screw Conveyor", "Mill B - 2nd Floor"],
  ["F69-B", "Screw Conveyor", "Mill B - 2nd Floor"],
  ["M048-B", "Screw Conveyor", "Mill B - 2nd Floor"],
  ["M049-B", "Screw Conveyor", "Mill B - 2nd Floor"],
  ["B20-B", "Tubular Screw Conveyor", "Mill B - 2nd Floor"],
  ["M045-B", "Vibro Feeder", "Mill B - 2nd Floor"],
  ["M046-B", "Vibro Feeder", "Mill B - 2nd Floor"],
  ["M047-B", "Vibro Feeder", "Mill B - 2nd Floor"],
  ["F23-B", "Infestation Destroyer", "Mill B - 2nd Floor"],
  ["BM-2", "Scale and Mixer", "Mill B - 2nd Floor"],
  ["BM-1", "Scale and Mixer", "Mill B - 2nd Floor"],
  ["B-M7110", "Mixer Maintenance", "Mill B - 2nd Floor Extension"],
  ["B-MixerSafeDoor", "Limit Switch - BS", "Mill B - 2nd Floor Extension"],
  ["B-VLS7119", "Pneumatic Valve", "Mill B - 2nd Floor Extension"],
  ["B-VLS7120", "Pneumatic Valve", "Mill B - 2nd Floor Extension"],
  ["B-VLS7113", "Pneumatic Valve", "Mill B - 2nd Floor Extension"],
  ["B-VLS7114", "Pneumatic Valve", "Mill B - 2nd Floor Extension"],
  ["B-VLS7116", "Pneumatic Valve", "Mill B - 2nd Floor Extension"],
  ["B-VLS7117", "Pneumatic Valve", "Mill B - 2nd Floor Extension"],
  ["B-AirSwitch", "Air Switch", "Mill B - 2nd Floor Extension"],
  ["B-VLS7118", "Pneumatic Valve", "Mill B - 2nd Floor Extension"],
  ["B-VLS7110A", "Pneumatic Slide Gate", "Mill B - 2nd Floor Extension"],
  ["B-LL7108", "Low Level Sensor", "Mill B - 2nd Floor Extension"],
  ["M063-B", "Bran Finisher", "Mill B - 3rd Floor"],
  ["F58D-B", "Infestation Destroyer", "Mill B - 3rd Floor"],
  ["M065-B", "Screw Conveyor", "Mill B - 3rd Floor"],
  ["M066-B", "Screw Conveyor", "Mill B - 3rd Floor"],
  ["B-VLS7101", "Pneumatic Slide Gate", "Mill B - 3rd Floor"],
  ["B-VLS7102", "Pneumatic Slide Gate", "Mill B - 3rd Floor"],
  ["B-VLS7103", "Pneumatic Slide Gate", "Mill B - 3rd Floor"],
  ["B-VLS7104", "Pneumatic Slide Gate", "Mill B - 3rd Floor"],
  ["B-VLS7105", "Pneumatic Slide Gate", "Mill B - 3rd Floor"],
  ["B-VLS7106", "Pneumatic Slide Gate", "Mill B - 3rd Floor"],
  ["B-VLS7108", "Pneumatic Slide Gate", "Mill B - 3rd Floor"],
  ["B-VLS7109", "Pneumatic Slide Gate", "Mill B - 3rd Floor"],
  ["B-VLS7107", "Pneumatic Slide Gate", "Mill B - 3rd Floor"],
  ["B-VLS7111", "Pneumatic Slide Gate", "Mill B - 3rd Floor"],
  ["B-VLS7110", "Pneumatic Slide Gate", "Mill B - 3rd Floor"],
  ["M067-B", "Additive Feeder", "Mill B - 3rd Floor"],
  ["M068-B", "Additive Feeder", "Mill B - 3rd Floor"],
  ["M069-B", "Additive Feeder", "Mill B - 3rd Floor"],
  ["M070-B", "Additive Feeder", "Mill B - 3rd Floor"],
  ["M067a-B", "Additive Feeder", "Mill B - 3rd Floor"],
  ["M071-B", "Airlock", "Mill B - 3rd Floor"],
  ["M050a-B", "Airlock", "Mill B - 3rd Floor"],
  ["F02-B", "Airlock", "Mill B - 3rd Floor"],
  ["F10-B", "Airlock", "Mill B - 3rd Floor"],
  ["F18-B", "Airlock", "Mill B - 3rd Floor"],
  ["M073b-B", "Airlock", "Mill B - 3rd Floor"],
  ["F09-B", "Automatic Scale", "Mill B - 3rd Floor"],
  ["F01-B", "Automatic Scale", "Mill B - 3rd Floor"],
  ["1B Scale-B", "Automatic Scale", "Mill B - 3rd Floor"],
  ["M058-B", "Bran Finisher", "Mill B - 3rd Floor"],
  ["M059-B", "Bran Finisher", "Mill B - 3rd Floor"],
  ["M060-B", "Bran Finisher", "Mill B - 3rd Floor"],
  ["M061-B", "Bran Finisher", "Mill B - 3rd Floor"],
  ["M062-B", "Bran Finisher", "Mill B - 3rd Floor"],
  ["M072-B", "Hammermill", "Mill B - 3rd Floor"],
  ["M073-B", "High Pressure Jet Filter", "Mill B - 3rd Floor"],
  ["M050-B", "High Pressure Jet Filter", "Mill B - 3rd Floor"],
  ["F58A-B", "Infestation Destroyer", "Mill B - 3rd Floor"],
  ["F58B-B", "Infestation Destroyer", "Mill B - 3rd Floor"],
  ["F58C-B", "Infestation Destroyer", "Mill B - 3rd Floor"],
  ["LSM64-B", "Limit Switch", "Mill B - 3rd Floor"],
  ["LSF32-B", "Limit Switch", "Mill B - 3rd Floor"],
  ["M051-B", "Purifier", "Mill B - 3rd Floor"],
  ["M052-B", "Purifier", "Mill B - 3rd Floor"],
  ["M053-B", "Purifier", "Mill B - 3rd Floor"],
  ["M054-B", "Purifier", "Mill B - 3rd Floor"],
  ["M055-B", "Purifier", "Mill B - 3rd Floor"],
  ["M056-B", "Purifier", "Mill B - 3rd Floor"],
  ["M057-B", "Purifier", "Mill B - 3rd Floor"],
  ["F17-B", "Automatic Scale", "Mill B - 3rd Floor"],
  ["B-M7105", "Airlock", "Mill B - 3rd Floor Extension"],
  ["B-M7106", "Manual Dump Hopper", "Mill B - 3rd Floor Extension"],
  ["B-M7107", "Micro -Material Feeder", "Mill B - 3rd Floor Extension"],
  ["B-M7108", "Micro -Material Feeder", "Mill B - 3rd Floor Extension"],
  ["B-M7109", "Micro -Material Feeder", "Mill B - 3rd Floor Extension"],
  ["B-M7118", "Low Pressure Fan", "Mill B - 3rd Floor Extension"],
  ["B-M7121", "Low Pressure Fan", "Mill B - 3rd Floor Extension"],
  ["B-FC7109", "Blending Batch Weigher System", "Mill B - 3rd Floor Extension"],
  ["B-FC7110", "Blending Batch Weigher System", "Mill B - 3rd Floor Extension"],
  ["B-FC7116", "Pulse Controller", "Mill B - 3rd Floor Extension"],
  ["B-FC7119", "Pulse Controller", "Mill B - 3rd Floor Extension"],
  ["B-VLS7112", "Pneumatic Valve", "Mill B - 3rd Floor Extension"],
  ["B-VLS7115", "Pneumatic Valve", "Mill B - 3rd Floor Extension"],
  ["B-LL7107", "Low Level Sensor", "Mill B - 3rd Floor Extension"],
  ["B-LL7109", "Low Level Sensor", "Mill B - 3rd Floor Extension"],
  ["B-M7120", "High Pressure Jet Filter - Airlock Motor", "Mill B - 3rd Floor Extension"],
  ["B-M7117", "High Pressure Jet Filter - Airlock Motor", "Mill B - 3rd Floor Extension"],
  ["B-M7116", "High Pressure Jet Filter - Scrapper Motor", "Mill B - 3rd Floor Extension"],
  ["B-M7119", "High Pressure Jet Filter - Scrapper Motor", "Mill B - 3rd Floor Extension"],
  ["M96-B", "Airlock", "Mill B - 4th Floor"],
  ["C11-B", "Gravity Classifying Destoner", "Mill B - 4th Floor"],
  ["ET01", "Electrical Panel Board - 1", "Mill B - 4th Floor"],
  ["C49-B", "Airlock", "Mill B - 4th Floor"],
  ["C23a-B", "Airlock", "Mill B - 4th Floor"],
  ["C44-B", "Automatic Scale", "Mill B - 4th Floor"],
  ["B22-B", "Bucket Elevator", "Mill B - 4th Floor"],
  ["S01-B", "Chain Conveyor", "Mill B - 4th Floor"],
  ["F56A-B", "Check Sifter", "Mill B - 4th Floor"],
  ["F56B-B", "Check Sifter", "Mill B - 4th Floor"],
  ["C21-B", "Dampening Conveyor", "Mill B - 4th Floor"],
  ["C35-B", "Gravity Classifying Destoner", "Mill B - 4th Floor"],
  ["HLC-B", "High Level Sensor", "Mill B - 4th Floor"],
  ["M074-B", "High Pressure Fan", "Mill B - 4th Floor"],
  ["C23-B", "High Pressure Jet Filter", "Mill B - 4th Floor"],
  ["M082-B", "Low Pressure Fan", "Mill B - 4th Floor"],
  ["B17-B", "Low Pressure Jet Filter", "Mill B - 4th Floor"],
  ["M096-B", "Low Pressure Jet Filter", "Mill B - 4th Floor"],
  ["M075-B", "Plansifter", "Mill B - 4th Floor"],
  ["M076-B", "Plansifter", "Mill B - 4th Floor"],
  ["M077-B", "Plansifter", "Mill B - 4th Floor"],
  ["M078-B", "Plansifter", "Mill B - 4th Floor"],
  ["M079-B", "Plansifter", "Mill B - 4th Floor"],
  ["VC001-B", "Pneumatic Flap Box", "Mill B - 4th Floor"],
  ["M081-B", "Rebolt Sifter", "Mill B - 4th Floor"],
  ["M080-B", "Rebolt Sifter", "Mill B - 4th Floor"],
  ["M091-B", "Cyclone Airlock Batch", "Mill B - 5th Floor"],
  ["M112-B", "Drum Detacher", "Mill B - 5th Floor"],
  ["B-UVL01", "Ultraviolet Sterilizer", "Mill B - 5th Floor"],
  ["C10-B", "Air Recyling Aspirator", "Mill B - 5th Floor"],
  ["C36-B", "Bucket Elevator", "Mill B - 5th Floor"],
  ["C43-B", "Bucket Elevator", "Mill B - 5th Floor"],
  ["M116-B", "Bucket Elevator", "Mill B - 5th Floor"],
  ["M085-B", "Cyclone Airlock Batch", "Mill B - 5th Floor"],
  ["M086-B", "Cyclone Airlock Batch", "Mill B - 5th Floor"],
  ["M087-B", "Cyclone Airlock Batch", "Mill B - 5th Floor"],
  ["M088-B", "Cyclone Airlock Batch", "Mill B - 5th Floor"],
  ["M089-B", "Cyclone Airlock Batch", "Mill B - 5th Floor"],
  ["M090-B", "Cyclone Airlock Batch", "Mill B - 5th Floor"],
  ["M092-B", "Cyclone Airlock Batch", "Mill B - 5th Floor"],
  ["M093-B", "Cyclone Airlock Batch", "Mill B - 5th Floor"],
  ["M094-B", "Cyclone Airlock Batch", "Mill B - 5th Floor"],
  ["C20-B", "Dampener Mixer", "Mill B - 5th Floor"],
  ["C12-B", "Disk Cylinder Separator", "Mill B - 5th Floor"],
  ["M114-B", "Drum Detacher", "Mill B - 5th Floor"],
  ["M113-B", "Drum Detacher", "Mill B - 5th Floor"],
  ["M115-B", "Drum Detacher", "Mill B - 5th Floor"],
  ["S50", "Dust Collector", "Mill B - 5th Floor"],
  ["M084-B", "High Pressure Fan", "Mill B - 5th Floor"],
  ["M083-B", "High Pressure Jet Filter", "Mill B - 5th Floor"],
  ["C37-B", "High Pressure Jet Filter", "Mill B - 5th Floor"],
  ["M097-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M100-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M098-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M099-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M102-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M101-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M105-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M103-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M104-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M106-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M107-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M108-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M109-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M110-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M111-B", "Impact Detacher", "Mill B - 5th Floor"],
  ["M095-B", "Low Pressure Fan", "Mill B - 5th Floor"],
  ["M064-B", "Screw Conveyor", "Mill B - 5th Floor"],
  ["F32A-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32B-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32C-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32D-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32E-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32F-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32G1-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32G2-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32H-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32I-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32J-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32K-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32L1-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32L2-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F32M-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F34A-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F34B-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F55A-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F55C-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F55D-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F55B-B", "Tubular Screw Conveyor", "Mill B - 5th Floor"],
  ["F54c-B", "Vibro Discharger", "Mill B - 5th Floor"],
  ["F54d-B", "Vibro Discharger", "Mill B - 5th Floor"],
  ["F54a-B", "Vibro Discharger", "Mill B - 5th Floor"],
  ["F54b-B", "Vibro Discharger", "Mill B - 5th Floor"],
  ["C09-B", "Vibro Separator", "Mill B - 5th Floor"],
  ["C33-B", "Vibro Separator", "Mill B - 5th Floor"],
  ["C19-B", "Water Addition System", "Mill B - 5th Floor"],
  ["C26-B", "Low Pressure Fan", "Mill B - 6th Floor"],
  ["C07-B", "Automatic Scale", "Mill B - 6th Floor"],
  ["C18-B", "Bucket Elevator", "Mill B - 6th Floor"],
  ["C30-B", "Bucket Elevator", "Mill B - 6th Floor"],
  ["M120-B", "Bucket Elevator", "Mill B - 6th Floor"],
  ["C06-B", "Bucket Elevator", "Mill B - 6th Floor"],
  ["M118-B", "High Pressure Fan", "Mill B - 6th Floor"],
  ["M117-B", "High Pressure Jet Filter", "Mill B - 6th Floor"],
  ["F52-B", "High Pressure Jet Filter", "Mill B - 6th Floor"],
  ["C25-B", "High Pressure Jet Filter", "Mill B - 6th Floor"],
  ["C39-B", "High Pressure Jet Filter", "Mill B - 6th Floor"],
  ["C32-B", "Horizontal Scourer", "Mill B - 6th Floor"],
  ["M119-B", "Low Pressure Fan", "Mill B - 6th Floor"],
  ["C24-B", "Low Pressure Fan", "Mill B - 6th Floor"],
  ["C38-B", "Low Pressure Fan", "Mill B - 6th Floor"],
  ["C40-B", "Low Pressure Fan", "Mill B - 6th Floor"],
  ["B18-B", "Low Pressure Fan", "Mill B - 6th Floor"],
  ["F78-B", "Low Pressure Fan", "Mill B - 7th Floor"],
  ["B-VLS7121", "Two-Way Valve", "Mill B - 7th Floor"],
  ["B-VLS7122", "Two-Way Valve", "Mill B - 7th Floor"],
  ["B-VLS7124", "Two-Way Valve", "Mill B - 7th Floor"],
  ["B-VLS7123", "Two-Way Valve", "Mill B - 7th Floor"],
  ["B-VLS7127", "Two-Way Valve", "Mill B - 7th Floor"],
  ["B-VLS7126", "Two-Way Valve", "Mill B - 7th Floor"],
  ["B-VLS7125", "Two-Way Valve", "Mill B - 7th Floor"],
  ["B-VLS7128", "Two-Way Valve", "Mill B - 7th Floor"],
  ["B-VLS7130", "Two-Way Valve", "Mill B - 7th Floor"],
  ["B-VLS7129", "Two-Way Valve", "Mill B - 7th Floor"],
  ["B-VLS7131", "Two-Way Valve", "Mill B - 7th Floor"],
  ["B-VLS7134", "Two-Way Valve", "Mill B - 7th Floor"],
  ["B-VLS7133", "Two-Way Valve", "Mill B - 7th Floor"],
  ["B-VLS7132", "Two-Way Valve", "Mill B - 7th Floor"],
  ["ET03", "Electrical Panel Board - 1", "Mill B - 7th Floor"],
  ["B-VLS7139", "Pneumatic Valve", "Mill B - 7th Floor"],
  ["B-VLS7136", "Pneumatic Valve", "Mill B - 7th Floor"],
  ["B-VLS7140", "Pneumatic Valve", "Mill B - 7th Floor"],
  ["B-VLS7137", "Pneumatic Valve", "Mill B - 7th Floor"],
  ["B-VLS7138", "Pneumatic Valve", "Mill B - 7th Floor"],
  ["B-VLS7141", "Pneumatic Valve", "Mill B - 7th Floor"],
  ["B-VLS7142", "Pneumatic Valve", "Mill B - 7th Floor"],
  ["B-VLS7135", "Two-Way Valve", "Mill B - 7th Floor"],
  ["F44-B", "Bucket Elevator", "Mill B - 7th Floor"],
  ["F45-B", "Chain Conveyor", "Mill B - 7th Floor"],
  ["F46-B", "Chain Conveyor", "Mill B - 7th Floor"],
  ["F47-B", "Chain Conveyor", "Mill B - 7th Floor"],
  ["F48-B", "Chain Conveyor", "Mill B - 7th Floor"],
  ["HLF-B", "High Level Sensor", "Mill B - 7th Floor"],
  ["F66-B", "High Pressure Jet Filter", "Mill B - 7th Floor"],
  ["F67-B", "High Pressure Jet Filter", "Mill B - 7th Floor"],
  ["F65-B", "Jet Filter", "Mill B - 7th Floor"],
  ["F30-B", "Low Pressure Fan", "Mill B - 7th Floor"],
  ["F53-B", "Low Pressure Fan", "Mill B - 7th Floor"],
  ["MDB04-B", "Control Panel", "Mill B - MCC Room"],
  ["MDB01-B", "Control Panel", "Mill B - MCC Room"],
  ["PP-IMECO", "Electrical Panel Board - 1", "Mill B - Packing Area"],
  ["PP-GGI", "Electrical Panel Board - 1", "Mill B - Packing Area"],
  ["QCA-QC-E-033", "Vibro Shaker", "Mill B - Packing Area"],
  ["P2-2", "Belt Conveyor", "Mill B - Tunnel"],
  ["P2-3", "Belt Conveyor", "Mill B - Tunnel"],
  ["P1-2", "Belt Conveyor", "Mill B - Tunnel"],
  ["P1-3", "Belt Conveyor", "Mill B - Tunnel"],
  ["SE-B", "Service Elevator", "Mill B Building"],
  ["BT-01", "Bulk Truck", "Mill B Building"],
  ["BT-02", "Bulk Truck", "Mill B Building"],
  ["F26-B", "Aspiration Valve", "N/A"],
  ["F29-B", "Low Pressure Jet Filter", "N/A"],
  ["BT-03", "Bulk Truck", "N/A"],
  ["BT-04", "Bulk Truck", "N/A"],
  ["TVSS-02", "TVSS (Transient voltage surge suppressor)", "N/A"],
  ["TVSS-01", "TVSS (Transient voltage surge suppressor)", "N/A"],
  ["TVSS-20", "TVSS (Transient voltage surge suppressor)", "N/A"],
  ["TVSS-03", "TVSS (Transient voltage surge suppressor)", "N/A"],
  ["C34-B", "Air Aspirator", "N/A"],
  ["VP-A", "Aspiration Valve", "N/A"],
  ["F72-B", "Low Pressure Fan", "N/A"],
  ["P47-A", "Low Pressure Fan", "N/A"],
  ["F71-B", "Low Pressure Jet Filter", "N/A"],
  ["F77-B", "Low Pressure Jet Filter", "N/A"],
  ["S15A", "Pneumatic Slide Gate", "N/A"],
  ["C22-B", "Pneumatic Slide Gate", "N/A"],
  ["S02-B", "Pneumatic Slide Gate", "N/A"],
  ["C21-A", "Pneumatic Slide Gate", "N/A"],
  ["F1 Mill A", "Two Way Valve A", "N/A"],
  ["F2 Mill A", "Two Way Valve A", "N/A"],
  ["F1 Mill B", "Two Way Valve B", "N/A"],
  ["F2 Mill B", "Two Way Valve B", "N/A"],
  ["F3 Mill B", "Two Way Valve B", "N/A"],
  ["BRAN-B", "Two Way Valve Bran", "N/A"],
  ["F31-B", "Vibro Discharger", "N/A"],
  ["P45-A", "High Pressure Jet Filter", "Old Bran Building"],
  ["MMG-P-007", "Fire Pump", "Pump Room"],
  ["MMG-P-002", "Service Pump", "Pump Room"],
  ["MMG-P-006", "Jockey Pump", "Pump Room"],
  ["MMG-P-004", "Mill Pump", "Pump Room"],
  ["MMG-P-005", "Mill Pump", "Pump Room"],
  ["MMG-P-003", "Service Pump", "Pump Room"],
  ["S13", "Chain Conveyor", "Silo - 1st floor"],
  ["TVSS- 09", "TVSS (Transient voltage surge suppressor)", "Silo - 1st floor"],
  ["S01", "Chain Conveyor", "Silo - 1st floor"],
  ["S42", "Chain Conveyor", "Silo - 1st floor"],
  ["S53", "Chain Conveyor", "Silo - 1st floor"],
  ["S40", "Dust Collector", "Silo - 1st floor"],
  ["S51", "Dust Collector", "Silo - 1st floor"],
  ["VS05", "Pneumatic Slide Gate", "Silo - 1st floor"],
  ["VS06", "Pneumatic Slide Gate", "Silo - 1st floor"],
  ["VS07", "Pneumatic Slide Gate", "Silo - 1st floor"],
  ["VS08", "Pneumatic Slide Gate", "Silo - 1st floor"],
  ["VS113", "Pneumatic Slide Gate", "Silo - 1st floor"],
  ["VS110", "Pneumatic Slide Gate", "Silo - 1st floor"],
  ["VS107", "Pneumatic Slide Gate", "Silo - 1st floor"],
  ["VS125", "Pneumatic Slide Gate", "Silo - 1st floor"],
  ["VS122", "Pneumatic Slide Gate", "Silo - 1st floor"],
  ["VS119", "Pneumatic Slide Gate", "Silo - 1st floor"],
  ["S07-A", "Automatic Scale", "Silo - 2nd floor"],
  ["S04", "Pneumatic Flap Box", "Silo - 3rd floor"],
  ["S03", "Drum Separator", "Silo - 4th floor"],
  ["S41", "Dust Collector", "Silo - 5th Floor"],
  ["S19", "Airlock", "Silo - 5th Floor"],
  ["S02", "Bucket Elevator", "Silo - 5th Floor"],
  ["S09", "Chain Conveyor", "Silo - 5th Floor"],
  ["S15", "Chain Conveyor", "Silo - 5th Floor"],
  ["S31", "Chain Conveyor", "Silo - 5th Floor"],
  ["S32", "Chain Conveyor", "Silo - 5th Floor"],
  ["S43", "Chain Conveyor", "Silo - 5th Floor"],
  ["S54", "Chain Conveyor", "Silo - 5th Floor"],
  ["S39", "Dust Collector", "Silo - 5th Floor"],
  ["VS14B", "Pneumatic Flap Box", "Silo - 5th Floor"],
  ["S08", "Bucket Elevator", "Silo - 6th Floor"],
  ["S14", "Bucket Elevator", "Silo - 6th Floor"],
  ["S19A", "High Pressure Jet Filter", "Silo - 6th Floor"],
  ["S20", "Low Pressure Fan", "Silo - 6th Floor"],
  ["VS14A", "Pneumatic Flap Box", "Silo - 6th Floor"],
  ["S43A", "Pneumatic Slide Gate", "Silo Building"],
  ["MDB01-A", "Control Panel", "Silo Building"],
  ["S52", "Dust Collector", "Silo Building"],
  ["HLS", "High Level Sensor", "Silo Building"],
  ["LSS", "Limit Switch", "Silo Building"],
  ["VS14C", "Pneumatic Flap Box", "Silo Building"],
  ["S07A", "Pneumatic Slide Gate", "Silo Building"],
  ["S11", "Pneumatic Slide Gate", "Silo Building"],
  ["S31A", "Pneumatic Slide Gate", "Silo Building"],
  ["S32A", "Pneumatic Slide Gate", "Silo Building"],
  ["S42A", "Pneumatic Slide Gate", "Silo Building"],
  ["S53A", "Pneumatic Slide Gate", "Silo Building"],
  ["SE-S", "Service Elevator", "Silo Building"],
  ["A-MCC01", "Electrical Panel Board", "Silo Control Room"],
  ["A-MDB01", "Electrical Panel Board", "Silo Control Room"],
];
